---
- hosts: all
  become: yes
  tasks:
   - name: update packing
     apt:
       update_cache: yes


 # node JS specific setting (url :https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-16-04)     
- hosts: app
  become: yes
  vars:
    folderpath: /home/ansible/nodesetup
  task:
    - name: creating a directory
      file:
        path: "{{ folderpath }}"
        state: directory
        mode: 0755
    - name: Download node js on ubuntu
      command: "curl -sL https://deb.nodesource.com/setup_8.x -o {{ folderpath}}nodesource_setup.sh"
    - name: excute shell script downloaded
      command: "sudo bash {{folderpath}}/nodesource_setup.sh"
    - name: Installing Nodejs
      apt:
        name: nodejs
        state: present
  
